### ISSUE TITLE
Page - Patch - Change Text Color

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/girl-coders#100]
Change to green text color:
Grab the color code from here: https://www.girlscoutsrv.org/en/events/event-list.html

![image](https://user-images.githubusercontent.com/24813620/37545585-47fb51a8-2937-11e8-8602-5aa63640bd93.png)

**Comment by saruoz** [comment]
I have changed color of all the headings on the page.
But cannot change the color of "Patch"  heading on the page.
http://dev.girlscoutcoders.org/patch/

**Comment by wpsam** [comment]
@saruoz 
Please use below CSS
article#post-787 h1.page-title a {
    color: #33cc33 !important;
}

**Comment by Code4SocialGood** [comment]
@wpsam  @saruoz For the heading of the page, that is inherited from menu item. Should that be controlled and customized in the theme, instead of using the css in the above comment?

**Comment by Code4SocialGood** [comment]
@wpsam @saruoz I am moving the change request of heading text color to a separate issue, since this is at web site level, not at specific web page level.
