### ISSUE TITLE
Page - Patches - App Inventor

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/girl-coders#110]
**Page Information**

- **Web Page: http://dev.girlscoutcoders.org/patches/appinventor/**

**Comment by Code4SocialGood** [comment]
Issue
The page is currently left aligned. Please make the page Center Aligned.

![image](https://user-images.githubusercontent.com/24813620/37805612-49dfa24a-2e09-11e8-9a0a-cc139b70115e.png)

**Comment by Code4SocialGood** [comment]
- **Change Request**: Make the video the same height as the description.

![image](https://user-images.githubusercontent.com/24813620/37805723-04e3f848-2e0a-11e8-92b7-116919ea1b3c.png)

**Comment by Code4SocialGood** [comment]
- **Change Request**: "Work-Shop" Material should be **"Workshop"** Material

![image](https://user-images.githubusercontent.com/24813620/37805778-4ccf4e78-2e0a-11e8-9b14-1140b90953d0.png)

**Comment by Code4SocialGood** [comment]
1. Change the text under the icons.
Currently: Curriculum, Flyer, Workshop Outline
Change to: Brochure, Curriculum, Outline

2. Please also correct the spelling of "Curriculum"

![image](https://user-images.githubusercontent.com/24813620/37805829-9646e106-2e0a-11e8-8be6-c27b28b7b494.png)

**Comment by Code4SocialGood** [comment]
3. Find some icons from internet for: Brochure, Curriculum, Outline

**Comment by Code4SocialGood** [comment]
- **Change Request: Project Gallery Section**
Drop the second row. Only keep one row.

![image](https://user-images.githubusercontent.com/24813620/37806020-99341036-2e0b-11e8-96dd-13c19a09776a.png)

**Comment by Code4SocialGood** [comment]
- **Section: Quote**
1. Remove text: - Girl Scout
2. Add "" around the text, and make text italic
3. Research whether there is more creative way to show quote in wordpress

**Current**
![image](https://user-images.githubusercontent.com/24813620/37806547-a037b416-2e0e-11e8-9390-d01b5d97bfcf.png)

**Change To**
![image](https://user-images.githubusercontent.com/24813620/37806669-39cf15b0-2e0f-11e8-8051-63ca48162320.png)

**Comment by Code4SocialGood** [comment]
Change the hyperlink for Brochure

**Comment by Code4SocialGood** [comment]
- **"Workshop Material" and "Project Gallery": make them center aligned.**

**Comment by nirajav** [comment]
Done

**Comment by nirajav** [comment]
Done

**Comment by Code4SocialGood** [comment]
Add under Workshop Material: Presentation.
Upon user click, open web page: http://dev.girlscoutcoders.org/patch/appinventor/app-inventor-workshop-presentation/
![image](https://user-images.githubusercontent.com/24813620/38167540-41a2574a-34fc-11e8-9cc1-ae1727407ad9.png)

**Comment by nirajav** [comment]
done

**Comment by Code4SocialGood** [comment]
Please implement the user interface based on the wireframe.

**Comment by Code4SocialGood** [comment]
Please add "Event" after "Presentation".

![image](https://user-images.githubusercontent.com/24813620/38486558-03227cd6-3ba3-11e8-8622-7a7bb85e488b.png)

**Comment by Code4SocialGood** [comment]
**Change Request**

- 1. Add a standard contact us form at bottom of the page.
