### ISSUE TITLE
Page - Patches - Material - Flyer

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/girl-coders#111]
- **Web Page: http://dev.girlscoutcoders.org/patch/appinventor/flyer/**

**Comment by Code4SocialGood** [comment]
- **Change the text from "Flyer" to "Brochure"**
1. Change the web page link from: http://dev.girlscoutcoders.org/patch/appinventor/app-inventor-workshop-flyer/ to http://dev.girlscoutcoders.org/patch/appinventor/app-inventor-workshop-brochure/ 
2. Change the Headline from "App Inventor Workshop Flyer" to "App Inventor Workshop Brochure". 

![image](https://user-images.githubusercontent.com/24813620/37807586-42f698f2-2e14-11e8-9d9f-8477415a22f1.png)

**Comment by Code4SocialGood** [comment]
- **Page Layout: Please remove the right panel.**

![image](https://user-images.githubusercontent.com/24813620/37809425-4e0fa680-2e1d-11e8-8d3c-72d9953aca46.png)

**Comment by wpsam** [comment]
Solved issues

**Comment by Code4SocialGood** [comment]
- **Button: Download**
Upon user click, enable user to download the word document.

- **Section: Brochure Content** 
Put the content in the word document to this section

- **Document**
[Patch - App Inventor - Brochure.docx](https://github.com/Code4SocialGood/girl-coders/files/1845608/Patch.-.App.Inventor.-.Brochure.docx)

**Comment by nirajav** [comment]
done

**Comment by nirajav** [comment]
done
