### ISSUE TITLE
Page - Patches - Material - Curriculum

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/girl-coders#112]
**Page Information**

- URL: http://dev.girlscoutcoders.org/patch/appinventor/curriculum/
- Video and Tutorial source: http://appinventor.mit.edu/explore/beginner-tutorials-short.html
- This page was developed in Visual Composer, however the PDF Embedder short code has to be fixed in classic editor. 
Short code should be: [pdf-embedder url="http://dev.girlscoutcoders.org/wp-content/uploads/2018/04/DigitalDoodle.pdf"]
However, Short code being modified by Visual Editor: [pdf-embedder url="[vcvUploadUrl]/2018/04/DigitalDoodle.pdf"], which results in the PDF not displaying in web page
This is an issue that we need to fix.

**Comment by nirajav** [comment]
Done

**Comment by Code4SocialGood** [comment]
Please develop this web page.
