### ISSUE TITLE
Page - Patches - Material - Activity Plan

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/girl-coders#113]
- **Web Page: http://dev.girlscoutcoders.org/patch/appinventor/activity-plan/**

**Comment by Code4SocialGood** [comment]
- **Page Layout: Please remove the right panel**

![image](https://user-images.githubusercontent.com/24813620/37809487-a1581fac-2e1d-11e8-9330-e20e063fa17a.png)

**Comment by Code4SocialGood** [comment]
Section: Download

1. Remove the text next to the button
2. Replace the button (oval shape and pink background) with a regular button.

![image](https://user-images.githubusercontent.com/24813620/37809731-a39fe2d0-2e1e-11e8-85a2-463392fd0758.png)

**Comment by Code4SocialGood** [comment]
- **Section: Outline**

Please put the content of the attached document in the outline section.

[Workshop_Outline.docx](https://github.com/Code4SocialGood/girl-coders/files/1840046/Workshop_Outline.docx)

**Comment by nirajav** [comment]
done
