### ISSUE TITLE
Page - Patch

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/girl-coders#117]
- **Web Page: http://dev.girlscoutcoders.org/patch/**

- **Wireframe**

![image](https://user-images.githubusercontent.com/24813620/37860031-c29a2966-2eeb-11e8-938d-5f6c37102d0b.png)

- **Current Page** (we validate changes by comparing changed page with current page)
![image](https://user-images.githubusercontent.com/24813620/38098940-e9ceb40a-333e-11e8-958b-269b7f9d1a64.png)

**Comment by Code4SocialGood** [comment]
- **Change Request**
1. Remove the line of "Materials" from each of the patch
2. Change "Age Group" to "Group Level"
3. Replace the images (daisies, brownies, etc) on the right panel. 

![image](https://user-images.githubusercontent.com/24813620/37860056-31478ca0-2eec-11e8-834e-e91325accdbb.png)

**Comment by wpsam** [comment]
I have just created a copy of the patch page using Visual compser editor so the page fully responsible on moble devices. 
http://dev.girlscoutcoders.org/patch-vc/
Let me know if this one is ok. Then I will replace current patch page with this one.

**Comment by Code4SocialGood** [comment]
@wpsam The new page looks great! Please replace current page with patch-vc page.

**Comment by wpsam** [comment]
I have replaced the page
