### ISSUE TITLE
Page - Badge - Computer Expert

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/girl-coders#123]
- **Web Page: http://dev.girlscoutcoders.org/badge/computer-expert/**

- **Reference: Official Badge Description**
![image](https://user-images.githubusercontent.com/24813620/37866474-26188c7c-2f59-11e8-87a9-15101f362902.png)

**Comment by Code4SocialGood** [comment]
Add description

Computers help you do so much. You can make amazing art, find incredible facts on the Internet, and send fun cards to friends and family. Earn this badge, and you'll be a safe, secure computer expert!

Paint or draw with an art program
Find some cool facts
Take a trip online
Make a connection
Have some computer fun
When I've earned this badge, I'll know how to do many useful things on a computer.

This badge comes in a packet that includes the Computer Expert, My Best Self, Dancer, Home Scientist, and My Family Story badges.

**Comment by Code4SocialGood** [comment]
- **Remove text: App Inventor**

![image](https://user-images.githubusercontent.com/24813620/37866489-48166434-2f59-11e8-8371-a6f0a5761572.png)

**Comment by nirajav** [comment]
what about right side video?
we need to take-out
do we have the mouse image with us? to place

**Comment by nirajav** [comment]
Done
