### ISSUE TITLE
Page - Patches - ScratchJr

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/girl-coders#126]
- **Web Page:** http://dev.girlscoutcoders.org/patch-old/scratchjr/

- **Wireframe**
![image](https://user-images.githubusercontent.com/24813620/38167735-33f41508-3500-11e8-879f-7347d1e71484.png)

- **Current Page**
![image](https://user-images.githubusercontent.com/24813620/38451256-77bc0c22-39f2-11e8-8961-1bbc8b7f58fe.png)

**Comment by Code4SocialGood** [comment]
Please change the current page base on the wireframe.

Please reference how App Inventor page is implemented. http://dev.girlscoutcoders.org/patch/appinventor/

**Comment by Code4SocialGood** [comment]
Add Patch Image:

![scratchjr](https://user-images.githubusercontent.com/24813620/38167760-fc9f036e-3500-11e8-983d-e6c1bd05d119.jpg)

**Comment by Lisajtx** [comment]
Added Title for ScratchJr page.

**Comment by Lisajtx** [comment]
Is this issue (#126) closed? Added ScratchJr title.
