### ISSUE TITLE
Page - Patches - Hour of Code

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/girl-coders#128]
**Page Information**

- URL:  http://dev.girlscoutcoders.org/patch-old/hour-of-code/

**Comment by Code4SocialGood** [comment]
Please change the current page base on the wireframe.

Please reference how App Inventor page is implemented. http://dev.girlscoutcoders.org/patch/appinventor/

**Comment by Code4SocialGood** [comment]
Add Patch Image:

![hour-of-code](https://user-images.githubusercontent.com/24813620/38167751-ce11f8da-3500-11e8-9400-2c9485f1ff3f.jpg)

**Comment by nirajav** [comment]
Done
