### ISSUE TITLE
Page - Patches - Made with Code

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/girl-coders#129]
**Page Information**

- URL:  http://dev.girlscoutcoders.org/patch-old/made-with-code/

**Comment by Code4SocialGood** [comment]
Please change the current page base on the wireframe.

Please reference how App Inventor page is implemented. http://dev.girlscoutcoders.org/patch/appinventor/

**Comment by Code4SocialGood** [comment]
Add Patch Image:
![made with code](https://user-images.githubusercontent.com/24813620/38167748-ad79f8de-3500-11e8-8996-e93d339cb6d8.png)

**Comment by nirajav** [comment]
done

**Comment by Code4SocialGood** [comment]
**Change Request**

- Are we able to add border, so that each project block will look like a card?

    Please see this web page as reference: https://www.madewithcode.com/projects/

![image](https://user-images.githubusercontent.com/24813620/39720838-2c780f08-5203-11e8-94d8-ca4d999481e2.png)

**Comment by Code4SocialGood** [comment]
**Change Request**

- For the grey out button of "See Example", check whether we are able to launch a new window for the example project. 
- You can reach the example project by click the "Start Project" button, then click the ? or Help button
- Other active buttons are able to bring up the example in new window, because the URL is appended with #example 
- The grey out example doesn't have a URL, seems it is done by some function behind the scenes

**Comment by Code4SocialGood** [comment]
**Change Request**

- Are we able to set less space on the left and right next to the text in each button,, and, make the spacing between two buttons larger?

![image](https://user-images.githubusercontent.com/24813620/39732283-1394e086-5232-11e8-910b-52a30d865b4f.png)

**Comment by Code4SocialGood** [comment]
**Change Request**

- This curriculum is for the curriculumn page: http://dev.girlscoutcoders.org/patches/made-with-code/curriculum/
- Implement this card design: http://demo.theme.co/renew-3/portfolio/ for each project
- For each project, remove the two button from the card
- When mouse hover the card, the two buttons display on the card
- You can install the demo app on staging site (http://staging.girlscoutcoders.org/) and test out to check out how it is implemented.

**Comment by Code4SocialGood** [comment]
**Change Request**

- Make the top portion as full width 
- See example: http://demo.theme.co/wedding/wedding-party/

![image](https://user-images.githubusercontent.com/24813620/39793621-dccb0104-530b-11e8-8864-c9949f2ca78d.png)
