### ISSUE TITLE
Page - Extension

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/girl-coders#143]
- **Web Page**: http://dev.girlscoutcoders.org/extension/

- **Wireframe**

![image](https://user-images.githubusercontent.com/24813620/38448832-47316f54-39cd-11e8-98c1-6e60f6924134.png)

- **Current Page**
![image](https://user-images.githubusercontent.com/24813620/38451183-ff5ea880-39f0-11e8-9ffd-c05ee7e7f96a.png)

**Comment by Code4SocialGood** [comment]
Please develop this web page based on the wireframe.

**Comment by nirajav** [comment]
done

**Comment by nirajav** [comment]
some one worked on it.
