### ISSUE TITLE
Page - Extension - Coding Club

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/girl-coders#144]
- **Web Page:** http://dev.girlscoutcoders.org/extension/coding-club/

- **Current Page**
![image](https://user-images.githubusercontent.com/24813620/38774448-0f7c6894-402f-11e8-9032-d758d644243f.png)

**Comment by Code4SocialGood** [comment]
Please develop this web page based on the wireframe.

**Comment by nirajav** [comment]
done

**Comment by Code4SocialGood** [comment]
- **The text should be a paragraph, not a separated first line.**

![image](https://user-images.githubusercontent.com/24813620/38451320-42e3c016-39f3-11e8-8eb6-985c4f0e1315.png)

**Comment by Code4SocialGood** [comment]
- **Please replace the images.**
- **Please note that senior should be in front of ambassador.**

![cadettes](https://user-images.githubusercontent.com/24813620/38451333-83c43b2e-39f3-11e8-8de5-f209813e073a.png)
![ambassador](https://user-images.githubusercontent.com/24813620/38451335-873bc9d4-39f3-11e8-9f68-3cddc2c5ab5d.jpg)
![senior](https://user-images.githubusercontent.com/24813620/38451336-89ef6910-39f3-11e8-8dfd-bcec17e3ef8a.jpg)


![image](https://user-images.githubusercontent.com/24813620/38451327-665d9bca-39f3-11e8-986f-16a47ddd62be.png)

**Comment by Code4SocialGood** [comment]
- **Please make the pink text bold.**

![image](https://user-images.githubusercontent.com/24813620/38451349-cabfcdfe-39f3-11e8-9aa9-70d5ac3a1751.png)

**Comment by Code4SocialGood** [comment]
- **Make the image and the text top align. Currently image is taller than text block.**

![image](https://user-images.githubusercontent.com/24813620/38774441-e7e57898-402e-11e8-9107-2db8275a076a.png)

**Comment by Code4SocialGood** [comment]
@Lisajtx Thank you for the fix. 
1. The change is validated and look good. We are removing this issue from this web page.
2. We will replace the WP theme for this app soon. After the theme change, we will go through the theme setting to following the web design guideline (WIP also), which will including the review on headings.
