### ISSUE TITLE
Page - Extension - Coding Camp

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/girl-coders#145]
- **Web Page:** http://dev.girlscoutcoders.org/extension/coding-camp/

- **Wireframe**

![image](https://user-images.githubusercontent.com/24813620/38177228-801588cc-35c3-11e8-9919-c76223003729.png)

**Comment by Code4SocialGood** [comment]
Please develop this web page based on the wireframe.

**Comment by nirajav** [comment]
done
