### ISSUE TITLE
Page - Extension - Hackathon

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/girl-coders#146]
- **Web Page:** http://dev.girlscoutcoders.org/extension/hackathon/

- **Wireframe**
![image](https://user-images.githubusercontent.com/24813620/38451568-f09db366-39f7-11e8-907d-c678eeeb895d.png)

- **Current Page**
![image](https://user-images.githubusercontent.com/24813620/38451584-245513c0-39f8-11e8-82ae-730cb184d109.png)

**Comment by Code4SocialGood** [comment]
Please develop the web page based on the wireframe.

**Comment by saruoz** [comment]
http://dev.girlscoutcoders.org/extension/hackathon/
Here is the new page.Please take a look.
