### ISSUE TITLE
Page - Extension - Mentoring Network

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/girl-coders#147]
- **Web Page:** http://dev.girlscoutcoders.org/extension/mentoring-network/

- **Wireframe**

![image](https://user-images.githubusercontent.com/24813620/38183137-93b51d12-3603-11e8-8497-8cc1e44189a2.png)

- **Current Page**
![image](https://user-images.githubusercontent.com/24813620/38451492-59d943b0-39f6-11e8-9af3-6b9746ac5b2b.png)

**Comment by Code4SocialGood** [comment]
Please develop this web page.
Images will be decided later. Just use any dummy image is fine at this time.

**Comment by nirajav** [comment]
done
