### ISSUE TITLE
Page - Watch Me Shine

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/girl-coders#150]
**Page Information**

- URL: http://dev.girlscoutcoders.org/watch-me-shine/

**Comment by Code4SocialGood** [comment]
- **Please develop the web page based on the wireframe.**

**Comment by nirajav** [comment]
done

**Comment by Code4SocialGood** [comment]
There are less space to the left of the image than to the right of the image. Pleas fix to make it center aligned. 

![image](https://user-images.githubusercontent.com/24813620/38451529-1def3642-39f7-11e8-907b-2b5cae26ecef.png)

**Comment by Code4SocialGood** [comment]
- **Please add Watch Us Shine Audio.** 
Audio could be downloaded from here: https://www.girlscouts.org/en/about-girl-scouts/like-a-girl-scout.html

![image](https://user-images.githubusercontent.com/24813620/38451549-8c063e00-39f7-11e8-88b7-eaef5c940ee2.png)

**Comment by nirajav** [comment]
looks audio is not free to download
