### ISSUE TITLE
Page - Shine - Inspire Her

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/girl-coders#152]
- **Web Page:** http://dev.girlscoutcoders.org/watch-me-shine/inspire-her/

- **Wireframe**

![image](https://user-images.githubusercontent.com/24813620/38182485-5dd69ad0-35ff-11e8-9a8e-ca1ca6b895ab.png)

- **Current Page**
![image](https://user-images.githubusercontent.com/24813620/38451373-3fd4b76c-39f4-11e8-9b0f-6973ce3d9f22.png)

**Comment by Code4SocialGood** [comment]
Please develop the web page based on the wireframe

**Comment by saruoz** [comment]
Here is the page link
http://dev.girlscoutcoders.org/watch-me-shine/inspire-her/
All done!

**Comment by Code4SocialGood** [comment]
Please reduce the gap .
Please reference: http://dev.girlscoutcoders.org/extension/

![image](https://user-images.githubusercontent.com/24813620/38451376-6509815c-39f4-11e8-9074-357c091858aa.png)

![image](https://user-images.githubusercontent.com/24813620/38451382-9aa032ac-39f4-11e8-8b1e-eb88da876647.png)
