### ISSUE TITLE
Page - Shine - Project Gallery

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/girl-coders#153]
- **Web Page:** http://dev.girlscoutcoders.org/watch-me-shine/project-gallery/

- **Wireframe**
![image](https://user-images.githubusercontent.com/24813620/38182576-087e8af6-3600-11e8-8c59-c553105267ed.png)

- **Current Page**
![image](https://user-images.githubusercontent.com/24813620/38182592-2126f0d4-3600-11e8-9f1f-8a2fc04a4643.png)

**Comment by Code4SocialGood** [comment]
Please develop the web page based on the wireframe.
We are still creating images. Please put any dummy images at this time on the web page.

**Comment by Prameela-B** [comment]
I made some changes to this page - do check
