### ISSUE TITLE
Page - FAQ

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/girl-coders#154]
**Page Information**

- URL: http://dev.girlscoutcoders.org/faq/

**Comment by Code4SocialGood** [comment]
**Please develop the web page based on wireframe.**

**Comment by nirajav** [comment]
done

**Comment by Code4SocialGood** [comment]
**Change Request**

Add a standard contact form in this 

- section.

![image](https://user-images.githubusercontent.com/24813620/39558530-f2f21c6c-4e54-11e8-8941-bb4c33514db1.png)
