### ISSUE TITLE
Page - Get Involved

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/girl-coders#155]
**Page Information**

- URL: http://dev.girlscoutcoders.org/get-involved/

**Comment by Code4SocialGood** [comment]
- **Please develop this web page based on the wireframe.**

**Comment by nirajav** [comment]
done

**Comment by nirajav** [comment]
done

**Comment by Code4SocialGood** [comment]
**Change Request**

Please add a standard contact us form at the bottom of the page.
Upon clicking the submit button, send email to: info@girlscoutcoders.org
