### ISSUE TITLE
Curriculum Development - Swift

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/girl-coders#164]
**Requirement: Development the curriculum for Swift Playground workshop**

- Read through the relevant web sites
    https://www.apple.com/swift/playgrounds/
    http://kata.coderdojo.com/wiki/Home_Page

- Write one sentence introduction on Swift Playground.
This introduction will be place on our web page here: http://dev.girlscoutcoders.org/patches/

- Write a brief description of a couple sentences on Swift Playground.
This brief description will be place on our web page like this: http://dev.girlscoutcoders.org/patches/appinventor/

- Choose an introduction video
This video will be placed on our web page like this: http://dev.girlscoutcoders.org/patches/appinventor/

- Choose tutorials that are:
Basic Level, no prior coding experience expected
Fun
Fits 2 hour workshop session

- Write down the links to the tutorials
Based on those tutorials, we will produce the Curriculum web page like this: http://dev.girlscoutcoders.org/patches/appinventor/curriculum/
The Curriculum web page is for the workshop instructors to learn the material

- Create the PowerPoint for the tutorials
Please use the Powerpoint template of this: http://dev.girlscoutcoders.org/patches/appinventor/presentation/
This PowerPoint will be played in projector during the workshop for girls to follow step by step

- Write down FAQs
    Write down any FAQs that might help the workshop instructors
    FAQ will be place on our web page like this: http://dev.girlscoutcoders.org/patches/appinventor/faq

**Comment by Lisajtx** [comment]
Began working on the Swift pages. Can we find sources from the web for the video tutorials - or do they need to be "official" MIT courses? I couldn't find any official ones for Swift yet.

**Comment by Code4SocialGood** [comment]
@Lisajtx Could you take a look at Swift Playground page? Since we only provide 2 hour workshop, we won't seriously teach Swift language to the girls, it is just too overwhelming and not feasible. Our impression is that Swift Playground can give them basic idea of what swift does, is fun, and is achievable in 2 hours.

**Comment by Lisajtx** [comment]
Added information and some videos and powerpoint for Swift Playground on the Curriculum page. Want to check to see if I'm on the right track.

**Comment by Code4SocialGood** [comment]
@Lisajtx Thank you for the research on Swift Playground. 

Our feeling is that although the Swift Playground suppose to be fun and easy start, they provide little marketing material and tutorials. It is hard to find any basic introduction video (comparing Scratch), and hard to find a simple tutorial to build a project and enjoy. 

The two resources that you identified so far, "Link to Tutorial" and "Download Powerpoint", intend to introduce Swift as a programming language, instead of introduce Swift Playground as a fund start. Are you able to find some materials that are fun? For our workshops, fun and easy is the first goal, then comes educational.

**Comment by Lisajtx** [comment]
I changed the resources from Swift to Swift Playground; I think these materials are much better.
