### ISSUE TITLE
Media Library

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/girl-coders#177]
Are we able to create folders in Media Library to organize content? If so, please create a sample folder with a sample image in it in media library.

**Comment by nt6726** [comment]
I believe this would require a plugin, such as https://wordpress.org/plugins/media-library-plus/

**Comment by Code4SocialGood** [comment]
@nt6726 Could you install the plugin and try it out?

**Comment by nt6726** [comment]
The plugins link doesn't show up on my dashboard, so I may have to be an admin to install plugins. Is there any way the editor role can access the plugins?

**Comment by Code4SocialGood** [comment]
@nt6726 Sorry about inconvenience! You have been assigned admin role. Please feel free to explore the plugins and integrate into the web site.

**Comment by nt6726** [comment]
Alright thanks. I have installed the plugin. There should now be a Media Library Folders option in the dashboard that contains all the media library images organized into folders. Right now I believe they are just organized by upload date, but they can be arranged and organized as desired. I created a "sample" folder and uploaded a sample image into it.

**Comment by Code4SocialGood** [comment]
This plugin works great, thanks!

Assigned this task to @code4socialgood to rearrange the images in folders and update all references in the web site.

**Comment by Code4SocialGood** [comment]
We ended up eliminating this feature, to limit the plug-in used on our web site.
