### ISSUE TITLE
Page - STEM Initiative - Add Border Color

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/girl-coders#188]
Web Page: http://dev.girlscoutcoders.org/about/stem-initiative/

Please add border colors:
- Girl Scouts STEM Pledge: #00abe6
- Girl Scout Coders Computer Science Pledge: #f37021

![image](https://user-images.githubusercontent.com/24813620/39972117-d1737bfe-56cd-11e8-92c0-6c0981a4c509.png)

**Comment by poetsgig** [comment]
Changes applied:
.page-id-778 #el-56a77219 .vce-col-inner { border: 1px solid #00abe6; }
.page-id-778 #el-10062255 .vce-col-inner { border: 1px solid #f37021; }

**Comment by Code4SocialGood** [comment]
1. Please make the border thicker
2. Please remove the border on "STEM Journeys" section (each images under this section will have its own green border, that is another issue documented in github)

**Comment by poetsgig** [comment]
1. I changed to 2px. Do you need thicker than that? 
2. Removed border on the STEM journeys section.

**Comment by Code4SocialGood** [comment]
Could you make it double thickness? Thanks.

**Comment by Code4SocialGood** [comment]
Please remove border around patches.

![image](https://user-images.githubusercontent.com/24813620/40029267-1f00cd6e-57a9-11e8-8858-d64ba1971962.png)

**Comment by poetsgig** [comment]
hmm...weird, the borders on the images doesn't come-up on my screen earlier. but anyway, i altered the code to reflect without the borders for inner elements.  also,  thickness is adjusted. the rest i will do tomorrow. i'm working on something else right now.

**Comment by Code4SocialGood** [comment]
Look great after the change. Close this issue.
