### ISSUE TITLE
Page - Scratch Patch Guide - Display PDF

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/girl-coders#193]
Web Page: http://dev.girlscoutcoders.org/patches/scratch/guide/

We are currently display embedded PDF on the web page. It works fine.

What are other popular plug in to display PDF? Is there better plug in that when user clicks next or prev page button, the page can flip, like user flips a book or magazine?

**Comment by nt6726** [comment]
I believe the PDF Light Viewer plugin (https://wordpress.org/plugins/pdf-light-viewer/) has this flipping page feature.

**Comment by nt6726** [comment]
I believe this plugin: https://wordpress.org/plugins/interactive-3d-flipbook-powered-physics-engine/#description has that flipping page feature.

**Comment by Code4SocialGood** [comment]
@nt6726 Please try it out on dev site. Thanks.

**Comment by Code4SocialGood** [comment]
The effect looks great, that is exact what we would like to achieve!

However, there are a couple issues:
1. The load takes a few seconds. Users won't know the PDF is loading (there is no loading spinner), and, users won't have patience to wait that long for a pdf file.
2. There are 2 pages in the PDF, however, the plugin shows 4 pages, which results in weird page browsing experience.

Please investigate on whether we could resolve the above two issues. Otherwise we might not be able to use this plugin. If the above two issues could be resolved, we'd happy to use this plugin!

**Comment by nt6726** [comment]
I tried a different plugin. It loads pretty quickly and only shows two pages. However, for some reason the resolution of the pdf is a bit blurry upon loading. I am not sure why this is but the user may have to zoom in once to get the full resolution. Let me know if you want me to try something else.

**Comment by Code4SocialGood** [comment]
This plugin works great, modern look and no major issues. 

We show this page to a couple users online, and the feedback is that since there are only two pages, it might be better to convert them into HTML instead of showing the pdf. PDF display is more suitable for document with many pages. So ... we are going to convert this page to be a regular web page without pdf. 

Sorry about the change of directions! Could you please keep the plugin in the wordpress dashboard, so that we could use it when we have large document to display in the future.

**Comment by Code4SocialGood** [comment]
Close this issue. new issue created: https://github.com/Code4SocialGood/girl-coders/issues/197
