### ISSUE TITLE
Page - Python - Develop new page

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/girl-coders#203]
**Create new page: http://dev.girlscoutcoders.org/patches/python/**

- **Banner section**
Grade level: Cadette, Senior, Ambassador

- **About Python section**
1) Python image
2) Python description: this can be obtained from wikipedia
3) Introduction video: find an introduction video 

- **Workshop Material section**
Only display text: Coming Soon ...

- **Request Patches section**
Same as all other patches

- **Update menu to add this patch under Patches**

- **On "Patches"  page, upon click Python patch, launch this new "Python" page in a new window**

**Comment by nt6726** [comment]
Done. Let me know if you want me to fix or change anything.

**Comment by Code4SocialGood** [comment]
**- The new page works great.** 

**- Please implement the following changes:**

1. Update menu to add this patch under Patches

![image](https://user-images.githubusercontent.com/24813620/40337446-50c17c22-5d35-11e8-939c-6670ff1fe2fa.png)

2. On "Patches" page, upon click Python patch, launch this new "Python" page in a new window

![image](https://user-images.githubusercontent.com/24813620/40337457-637d089a-5d35-11e8-83c9-04afab1850ac.png)

**Comment by Code4SocialGood** [comment]
Works great. Closing this issue.
