### ISSUE TITLE
Page - PhP - Develop new page

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/girl-coders#204]
**Create new page: http://dev.girlscoutcoders.org/patches/php/**

- **Banner section**
Grade level: Cadette, Senior, Ambassador

- **About PhP section**
1)  PhP image
2)  PhP description: this can be obtained from wikipedia
3) Introduction video: find an introduction video 

- **Workshop Material section**
Only display text: Coming Soon ...

- **Request Patches section**
Same as all other patches

- **Update menu to add this patch under Patches**

- **On "Patches"  page, upon click PhP patch, launch this new "PhP" page in a new window**

**Comment by nt6726** [comment]
Done. Let me know if anything needs to be fixed.

**Comment by Code4SocialGood** [comment]
Works great. Closing the issue.
