### ISSUE TITLE
Page - Arduino - Develop new page

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/girl-coders#206]
**Create new page: http://dev.girlscoutcoders.org/patches/Arduino/**

- **Banner section**
Grade level: Cadette, Senior, Ambassador

- **About Arduino section**
1)  Arduino image
2)  Arduino description: this can be obtained from wikipedia
3) Introduction video: find an introduction video 

- **Workshop Material section**
Only display text: Coming Soon ...

- **Request Patches section**
Same as all other patches

- **Update menu to add this patch under Patches**

- **On "Patches"  page, upon click Arduino patch, launch this new "Arduino" page in a new window**

**Comment by nt6726** [comment]
Done. Please let me know if anything needs to be fixed.

**Comment by Code4SocialGood** [comment]
Works great. Issue closed.
