### ISSUE TITLE
Page - Swift Playground - Develop new page

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/girl-coders#207]
**Create new page: http://dev.girlscoutcoders.org/patches/swift-playground/**

- **Banner section**
Grade level: Cadette, Senior, Ambassador

- **About Swift Playground section**
1)  Swift Playground image
2)  Swift Playground description: this can be obtained from wikipedia
3) Introduction video: find an introduction video 

- **Workshop Material section**
Only display text: Coming Soon ...

- **Request Patches section**
Same as all other patches

- **Update menu to add this patch under Patches**

- **On "Patches"  page, upon click Swift Playground patch, launch this new "Swift Playground" page in a new window**

**Comment by nt6726** [comment]
Done. Please let me know if there are any issues.

**Comment by Code4SocialGood** [comment]
Works great. Issue closed.
