### ISSUE TITLE
Page - Wix - Develop new page

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/girl-coders#209]
**Create new page: http://dev.girlscoutcoders.org/patches/wix/**

- **Banner section**
Grade level: Cadette, Senior, Ambassador

- **About Wix section**
1)  Wix image
2)  Wix description: this can be obtained from wikipedia
3) Introduction video: find an introduction video 

- **Workshop Material section**
Only display text: Coming Soon ...

- **Request Patches section**
Same as all other patches

- **Update menu to add this patch under Patches**

- **On "Patches"  page, upon click Wix patch, launch this new "Wix" page in a new window**

**Comment by nt6726** [comment]
Done. I could not find a badge image for WordPress so I just used the coming soon image. Let me know if there are any issues.

**Comment by Code4SocialGood** [comment]
Works great, closing the issue.
