### ISSUE TITLE
Page - Weebly - Develop new page

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/girl-coders#210]
**Create new page: http://dev.girlscoutcoders.org/patches/Weebly/**

- **Banner section**
Grade level: Cadette, Senior, Ambassador

- **About Weebly section**
1)  Weebly image
2)  Weebly description: this can be obtained from wikipedia
3) Introduction video: find an introduction video 

- **Workshop Material section**
Only display text: Coming Soon ...

- **Request Patches section**
Same as all other patches

- **Update menu to add this patch under Patches**

- **On "Patches"  page, upon click Weebly patch, launch this new "Weebly" page in a new window**

**Comment by nt6726** [comment]
Done. I could not find a badge image for Weebly so I just used the coming soon image. Let me know if there are any issues.

**Comment by Code4SocialGood** [comment]
Works great, closing the issue.
