### ISSUE TITLE
Blog - Permalink for post

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/girl-coders#216]
- Currently the posts are under website url directly: 
Permalink: `http://dev.girlscoutcoders.org/what-is-scratch-anyway/`

- Are we able to make all the posts under a sub url, such as: 
Permalink: `http://dev.girlscoutcoders.org/blog/what-is-scratch-anyway/`

![image](https://user-images.githubusercontent.com/24813620/40499154-a8f7c276-5f46-11e8-975b-620063a29a5c.png)

**Comment by nt6726** [comment]
Fixed!

**Comment by Code4SocialGood** [comment]
Excellent! Issue closed.
