### ISSUE TITLE
Page - Illustrator - Develop new page

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/girl-coders#224]
**Create new page: http://dev.girlscoutcoders.org/patches/Illustrator/**

- **Banner section**
Grade level: Junior, Cadette, Senior, Ambassador

- **About Illustratorsection**
1)  Illustratorimage
2)  Illustratordescription: this can be obtained from wikipedia
3) Introduction video: find an introduction video 

- **Workshop Material section**
Only display text: Coming Soon ...

- **Request Patches section**
Same as all other patches

- **Update menu to add this patch under Patches**

- **On "Patches"  page, upon click Photoshop patch, launch this new "Illustrator" page in a new window**

**Comment by nt6726** [comment]
Done. Let me know if there are any issues.

**Comment by nt6726** [comment]
Fixed. Please let me know if there are any issues.

**Comment by Code4SocialGood** [comment]
Issue closed.
