### ISSUE TITLE
Page - Patch - Upload Patch Images

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/girl-coders#45]
![gsc-funpatch-1](https://user-images.githubusercontent.com/24813620/36936029-379c61e8-1ec5-11e8-8d93-6846288b89d5.jpg)
![gsc-funpatch-app-inventor](https://user-images.githubusercontent.com/24813620/36936030-3a1df51c-1ec5-11e8-8b0e-b2909b98cacf.png)
![gsc-funpatch-mit](https://user-images.githubusercontent.com/24813620/36936031-3d23b3c8-1ec5-11e8-9a40-9e67513667ae.jpg)

![madewcode](https://user-images.githubusercontent.com/24813620/36936034-47a42f58-1ec5-11e8-9f34-714437c62b12.png)

![hour-of-code](https://user-images.githubusercontent.com/24813620/37015036-263c0d2a-20ca-11e8-8808-100e1948ddbd.jpg)

**Comment by saruoz** [comment]
I have uploaded the images in the media library.
