### ISSUE TITLE
Digital Marketing

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/girl-coders#46]
Flyer

**Comment by Code4SocialGood** [comment]
**Task: Upload Logo**

![logo-3](https://user-images.githubusercontent.com/24813620/36936112-4145bf40-1ec6-11e8-86df-da3b45de1bff.png)

**Comment by saruoz** [comment]
I have uploaded the header image in the media library. But only the wp-admin can change this image.
As there is no Appearance tab in this dashboard.

**Comment by nirajav** [comment]
done
