### ISSUE TITLE
Project Gallery - Girl Scout Troop Web Site

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/girl-coders#48]
Develop a sample girl scout troop web site with wordpress.
You could google "Girl Scout Troop" to find some existing sites as reference.
This sample app doesn't need to be complicated. A couple of typical web pages should be good.
Please submit PR with the .wpress file, and in the PR please upload screen shots of each web page.

Sample content:
1. Troop travel: https://volunteers.girlscoutsrv.org/2018/03/01/megabus-car-plane-train-troop-travel-kept-us-together/

**Comment by apekshasharma27** [comment]
done 
![fireshot capture 9 - girl scout troo_ - http___dev girlscoutcoders org_expose_girl-scout-troop-1234_](https://user-images.githubusercontent.com/20996100/37738578-d1446ce8-2d2d-11e8-8025-9fc8d3171283.png)
