### ISSUE TITLE
Page - About - Remove the last line

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/girl-coders#51]
Page: http://dev.girlscoutcoders.org/about/

![image](https://user-images.githubusercontent.com/24813620/36957612-1ebca34a-1ffb-11e8-8063-8d19fd5af0df.png)

**Comment by saruoz** [comment]
Hi Jenny,
I have removed the last line on the About Us page.
here is the screen shot
![screen shot 2018-03-05 at 1 33 20 pm](https://user-images.githubusercontent.com/25517117/36993375-a46ec970-207b-11e8-8838-659def57fce7.png)

**Comment by Code4SocialGood** [comment]
@saruoz Please see attached the screen shot of before and after. The layout for the 3 images on top of the page have changed. Could you take a look at why?
[after.pdf](https://github.com/Code4SocialGood/girl-coders/files/1782281/after.pdf)
[before.pdf](https://github.com/Code4SocialGood/girl-coders/files/1782283/before.pdf)

**Comment by saruoz** [comment]
I have fixed it back to original layout.
Here is the scrren shot now
![screen shot 2018-03-06 at 10 12 17 am](https://user-images.githubusercontent.com/25517117/37040300-807323d4-2127-11e8-85de-7302b9dde754.png)

**Comment by Code4SocialGood** [comment]
This issue is resolved.
