### ISSUE TITLE
Page - Home - Upload Logo

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/girl-coders#52]
![logo-3](https://user-images.githubusercontent.com/24813620/36936112-4145bf40-1ec6-11e8-86df-da3b45de1bff.png)

**Comment by nirajav** [comment]
![](https://user-images.githubusercontent.com/24813620/36936112-4145bf40-1ec6-11e8-86df-da3b45de1bff.png)

**Comment by nirajav** [comment]
jenny can you check this once
