### ISSUE TITLE
Page - Our Programs - Develop

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/girl-coders#53]
[Our Programs.pdf](https://github.com/Code4SocialGood/girl-coders/files/1783524/Our.Programs.pdf)

**Comment by apekshasharma27** [comment]
Completed
![fireshot capture 1 - our programs girlscoutc_ - http___dev girlscoutcoders org_about_our-programs_](https://user-images.githubusercontent.com/20996100/37058109-647f7e0e-2157-11e8-8a5a-d733457ab7eb.png)

**Comment by Code4SocialGood** [comment]
@apekshasharma27 Could you please remove the content from the right portion of the page? 
BTW, the right portion of the page, is this global setting for the whole site, or each page has its own setting? We don't want this right portion for any of our web pages.

![image](https://user-images.githubusercontent.com/24813620/37061473-44d7e396-2159-11e8-865c-b827b2d86b79.png)

**Comment by apekshasharma27** [comment]
I think this is global for the site and I guess it can be done in the appearance section of the 
admin dashboard depending on the theme we have  .
