### ISSUE TITLE
Page - Patch - Develop

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/girl-coders#56]
[Patch.pdf](https://github.com/Code4SocialGood/girl-coders/files/1783560/Patch.pdf)

**Comment by saruoz** [comment]
I have done the Patch page on the site. Here is the screen shot.
![screen shot 2018-03-10 at 2 43 40 pm](https://user-images.githubusercontent.com/25517117/37246133-88971f8c-2471-11e8-80ed-40e2364a31d3.png)

**Comment by saruoz** [comment]
Any idea where can I find these to put on the Patch page?
![screen shot 2018-03-10 at 2 44 39 pm](https://user-images.githubusercontent.com/25517117/37246151-dc8af3de-2471-11e8-8b47-e0be04e741b1.png)

**Comment by saruoz** [comment]
These are suppose to go on the right side on the Patch page.
![screen shot 2018-03-10 at 2 52 07 pm](https://user-images.githubusercontent.com/25517117/37246214-2c5f64e8-2473-11e8-9549-2c40d150f97f.png)

**Comment by Code4SocialGood** [comment]
@saruoz You could find the images here: http://www.girlscouts.org/en/our-program/grade-levels.html
Note: you can just cut and paste from the above web site, this doesn't need to be a high quality image.

**Comment by saruoz** [comment]
Patch page is done! 
http://dev.girlscoutcoders.org/patch/
Please take a look and let me know if anything needs to be changed.
