### ISSUE TITLE
Header

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/girl-coders#63]
Page Header Section

**Comment by apekshasharma27** [comment]
Completed
![fireshot capture 2 - project gallery girlscoutcoders_ - http___dev girlscoutcoders org_watc](https://user-images.githubusercontent.com/20996100/37170276-68fc11c2-22d8-11e8-97f3-69aec1b02d7c.png)

**Comment by apekshasharma27** [comment]
Completed. (The grey line across the page is only visible in the sceen shot not the actual page)
![fireshot capture 6 - project gallery girlscoutcoders_ - http___dev girlscoutcoders org_watc](https://user-images.githubusercontent.com/20996100/37170412-bc47770e-22d8-11e8-805f-d3055bbb7962.png)

**Comment by Code4SocialGood** [comment]
@apekshasharma27 Please remove the right panel of the page (Search, Recent Comments, etc)
We won't use right panel on any of our web pages.

**Comment by apekshasharma27** [comment]
Its removed now .
![fireshot capture 8 - project gallery girlscoutcoders_ - http___dev girlscoutcoders org_watc](https://user-images.githubusercontent.com/20996100/37214536-5ee09cf2-2383-11e8-8e74-230e1973c53c.png)

**Comment by Code4SocialGood** [comment]
**Change Request**

- Are we able to show second level menu, so that we don't need to show page title on each web page. 
- See sample below: http://demo.theme.co/icon-1/pages/pricing/
- Please reference demo app on test site to check out how second level menu is implemented

![image](https://user-images.githubusercontent.com/24813620/39789218-25c3cb4c-52f4-11e8-8f26-0c6ae6ef8dc5.png)
