### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/girl-coders#64]
**Change Request**

- Add an email icon next to the three social icons: info@girlscoutcoders.org

![image](https://user-images.githubusercontent.com/24813620/39089630-ea1888e0-4591-11e8-9670-8d3974764b96.png)

**Comment by Code4SocialGood** [comment]
- **Link to our social media accounts**

Instagram: https://www.instagram.com/girlscoutcoders/
Facebook: https://www.facebook.com/girlscoutcoders
Twitter: https://twitter.com/girlscoutcoders

**Comment by Code4SocialGood** [comment]
- **Copyright Section - Change Text Alignment**


AS_IS:

![image](https://user-images.githubusercontent.com/24813620/37440776-460e44ca-27cc-11e8-99c2-fd17a582618b.png)

TO_BE:

![image](https://user-images.githubusercontent.com/24813620/37440796-5b814870-27cc-11e8-8dfa-ab29078f2ca0.png)

**Comment by Code4SocialGood** [comment]
**Social media icons: Make them half the current size.**

**Comment by ed1024** [comment]
Added email icon to next to three social icons. See attachment.
![gscsocial](https://user-images.githubusercontent.com/38773488/39678258-051c9f16-5157-11e8-8d60-096c68023346.JPG)

**Comment by Code4SocialGood** [comment]
@ed1024 Thanks for the change, works great!

**Comment by ed1024** [comment]
@Code4SocialGood Nice.
