### ISSUE TITLE
Page - Home

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/girl-coders#66]
- **Page Information**

URL: http://dev.girlscoutcoders.org

**Comment by Code4SocialGood** [comment]
Remove phone and email from the top of the page.

![image](https://user-images.githubusercontent.com/24813620/37807625-7d3432c2-2e14-11e8-8444-a6c2c4a9b4bb.png)

**Comment by Code4SocialGood** [comment]
![image](https://user-images.githubusercontent.com/24813620/37247305-e3c714ea-247e-11e8-8d55-a1eb53899992.png)

**Comment by Code4SocialGood** [comment]
- **Change Request: Please develop the page as shown in wireframe**

**Comment by JakeThomas117** [comment]
Hi Jenny,
I'm not sure how to remove the phone and email from the top of the page, but I developed the rest as requested.
<img width="1007" alt="screen shot 2018-03-23 at 9 31 08 pm" src="https://user-images.githubusercontent.com/36618881/37860436-fb2518a4-2ee1-11e8-89b9-de4a63913702.png">

**Comment by Code4SocialGood** [comment]
@JakeThomas117 
The page looks great, thank you!
The phone and email has been removed, I assume it might be in theme setting.

**Comment by Code4SocialGood** [comment]
- **Call to Action Button: Click here to begin**

Link to http://dev.girlscoutcoders.org/about/our-programs/

**Comment by wpsam** [comment]
Added link on call to action button

**Comment by Code4SocialGood** [comment]
Section: Featured Images
1. Current there is only one image. Find more images to add to the slide
2. Are we able to set the slide to scroll automatically instead of manual click?

![image](https://user-images.githubusercontent.com/24813620/38168701-943a2334-351a-11e8-94b7-ea470e490ff4.png)

**Comment by Code4SocialGood** [comment]
- **Section: Call to Action**

1. Are we able to make the font larger: A Program By Girl Scouts, For Girl Scouts

![image](https://user-images.githubusercontent.com/24813620/38168708-b1a82402-351a-11e8-9737-d2c5674fbfd2.png)

**Comment by Code4SocialGood** [comment]
- **Section: Header**

Are we able to change the background for the header secton on home page? We can hardly see the background since the header background and the featured image are similar colors.

![image](https://user-images.githubusercontent.com/24813620/38168722-ef2dfa68-351a-11e8-9cf8-6b8efccdedfe.png)

Here is how it looks like if the featured image is a different color:
![image](https://user-images.githubusercontent.com/24813620/38168725-08ce96f8-351b-11e8-937e-3e7425cd8386.png)

**Comment by Code4SocialGood** [comment]
- **Section: Text**

Move the text "It's Our World - Change It!" to be above the text "A Program By Girl Scouts, For Girl Scouts"

![image](https://user-images.githubusercontent.com/24813620/38168738-83c7f002-351b-11e8-95f9-2e8dc53b4f3a.png)

**Comment by Code4SocialGood** [comment]
Reduce the space to be half.

**Comment by Code4SocialGood** [comment]
- **Change "CS Diversity" to be "Girl Scouts Global"**

![image](https://user-images.githubusercontent.com/24813620/38168752-17b17978-351c-11e8-93b8-152ed65411fd.png)

**Comment by Code4SocialGood** [comment]
- **Make the font size larger**
- **Make the font bold**

![image](https://user-images.githubusercontent.com/24813620/38168770-5f4c3296-351c-11e8-8ae6-4fec0cde8753.png)

**Comment by Code4SocialGood** [comment]
- **CS Shortage**
Make it same border width as other sections 

![image](https://user-images.githubusercontent.com/24813620/38168793-be70bd28-351c-11e8-8671-2fdad475e808.png)

**Comment by Code4SocialGood** [comment]
- **Create Pie Image**

CS Shortage: 1/2
CS Diversity: 1/7

![image](https://user-images.githubusercontent.com/24813620/38168811-0a471440-351d-11e8-88cb-627fb63d0a10.png)

**Comment by Code4SocialGood** [comment]
- **Replace the images**

![image](https://user-images.githubusercontent.com/24813620/38168849-78df2d9c-351e-11e8-9112-61ee373f1261.png)

https://www.google.com/imgres?imgurl=https%3A%2F%2F2.bp.blogspot.com%2F-QAH58uOFIww%2FWd6gEwWoXnI%2FAAAAAAAAnpU%2FN1YlEMPZkZQsrSbbf-91J8IEKFxx2bUDQCEwYBhgL%2Fs1600%2FKTP_GSA_Flag_0215-Edit.jpg&imgrefurl=http%3A%2F%2Fblog.girlscouts.org%2F2017%2F10%2Fgirl-scouts-are-girl-leadership-experts.html&docid=AurVoiCvoCNWxM&tbnid=E39i0FAjcypTpM%3A&vet=10ahUKEwj2vbDU8JfaAhWq54MKHTf0DQAQMwiXASguMC4..i&w=1600&h=1066&bih=662&biw=1366&q=girl%20scouts%20usa&ved=0ahUKEwj2vbDU8JfaAhWq54MKHTf0DQAQMwiXASguMC4&iact=mrc&uact=8

![image](https://user-images.githubusercontent.com/24813620/38168816-5223ee96-351d-11e8-8f99-a63541c66d26.png)

![image](https://user-images.githubusercontent.com/24813620/38168843-632d6356-351e-11e8-9bfc-365dc7e77210.png)

**Comment by Code4SocialGood** [comment]
- **Please make the four blocks bottom aligned.**

![image](https://user-images.githubusercontent.com/24813620/39089644-2b53d580-4592-11e8-974e-5e4f2f00bfab.png)

**Comment by Code4SocialGood** [comment]
- **Add shadow to the text to highlight the text**
The change will be made in Slider Revolution

![image](https://user-images.githubusercontent.com/24813620/39090110-3bc49bf8-459b-11e8-8daf-7ce29d98524e.png)

![image](https://user-images.githubusercontent.com/24813620/39090112-56030360-459b-11e8-8590-8e360fee3350.png)

**Comment by Code4SocialGood** [comment]
- **Move the image to be center aligned vertically**

![image](https://user-images.githubusercontent.com/24813620/39090184-8d85b920-459d-11e8-8431-5127cb01b53f.png)

**Comment by Lisajtx** [comment]
Please check changes; I can change the background color from something other than red on the Home Page. Also - where do you want the announcement - usually they scroll on a sidebar? I added a plugin, but am not sure where to put the announcement.  Lisa

**Comment by Code4SocialGood** [comment]
**Change Request**

- Please implement the middle section close to the wireframe. 

![image](https://user-images.githubusercontent.com/24813620/39668947-1301315a-50a3-11e8-949e-7f2fdd28122e.png)

![desktop-green1](https://user-images.githubusercontent.com/24813620/39668948-1c800440-50a3-11e8-8648-d308601914c8.png)

**Comment by Code4SocialGood** [comment]
**Change Request: Featured Image**
Please render the home page image better, so that it fits in one screen and give better look and feel.

**Comment by Code4SocialGood** [comment]
@Lisajtx Here is the response from WP Live: 

_We do provide our Pro free of charge to NPO's, but we ask they link back to our site and review our plugin. Would you perhaps be open to this? :)_

Do you know what they mean by "link back and review"? 

BTW, I also replied to them asking them for more explanation.

**Comment by Code4SocialGood** [comment]
@Lisajtx FYI - This new project is added today, "TEACHER APPRECIATION WEEK". https://www.madewithcode.com/projects/. This is a sample scenario for our announcement.

**Comment by Code4SocialGood** [comment]
**Change Request**

- Please make the button text bold

![image](https://user-images.githubusercontent.com/24813620/39736488-c81ceb4e-5245-11e8-9f00-ab29728b65b7.png)

**Comment by Code4SocialGood** [comment]
**Change Request**

Please make the web page as described in the wireframe.
1. Card: Produce the card effect for the two images and the patch section
2. Two Images: make the image extend to the full width of the card

[Home_v1.pdf](https://github.com/Code4SocialGood/girl-coders/files/1985105/Home_v1.pdf)

**Comment by Lisajtx** [comment]
![image](https://user-images.githubusercontent.com/38472616/39777841-578b34a0-52ca-11e8-8949-f32027f4c7bc.png)

Does anyone know why changing from the default template to the sidebar template would produce this error message? I was trying to add announcement (we have plugin) to the sidebar.

**Comment by Code4SocialGood** [comment]
**Change Requests**
Change the menu item to be white background with green menu item and logo.
The place to change should be in: Appearance -> Customize -> Additional CSS to change those colors...

![gsc-2](https://user-images.githubusercontent.com/24813620/39782482-f6ed1484-52d7-11e8-98b8-4c1994b194de.png)
![gsc-3](https://user-images.githubusercontent.com/24813620/39782488-fa808f4a-52d7-11e8-9324-14820ef266f8.png)

**Comment by Code4SocialGood** [comment]
@ed1024 Could you help with the home page design and development when you have time?

**Comment by Code4SocialGood** [comment]
**Change Request**

- Add announcement: 
This week is Techer Appreciation Week. How about design and code a special thank you note for your favorite teacher, and earn a free Made with Code patch? Chekc out this cool project: https://www.madewithcode.com/projects/

**Comment by Code4SocialGood** [comment]
**Change Request**

- Patches section: add animation so that for each row of patches, move from left or from right
- Reference: http://demo.theme.co/renew-2/
- You can install the above demo on staging site (http://staging.girlscoutcoders.org/) to see how it is implemented.

**Comment by Code4SocialGood** [comment]
**Change Request**

- Add patch name under the patch image. See sample below.

![image](https://user-images.githubusercontent.com/24813620/39787969-a198ad34-52ed-11e8-8a7b-361dd9c8fa77.png)

**Comment by ed1024** [comment]
Changed Font and Spacing, had to substitute font.
