### ISSUE TITLE
Page - About - STEM Initiative

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/girl-coders#69]
- **Page Information**

URL: http://dev.girlscoutcoders.org/about/stem-initiative/

**Comment by nirajav** [comment]
Done

**Comment by Code4SocialGood** [comment]
Remove right panel

**Comment by Code4SocialGood** [comment]
Develop the web page

**Comment by Code4SocialGood** [comment]
- **Reduced the highlighted border to be half**

![image](https://user-images.githubusercontent.com/24813620/39090758-2755ec64-45ad-11e8-9371-862703a681b9.png)
