### ISSUE TITLE
Page - Serving Community - Upload Image

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/girl-coders#70]
Upload images for : 

- Daisey
- Brownie
- Junior
- Cadettes
- Senior
- Ambassador

Images could be obtained from : http://www.girlscouts.org/en/our-program/grade-levels.html
(We use those images on dev environment, we will replace with our own images later)
![image](https://user-images.githubusercontent.com/24813620/37247507-acacc7f4-2481-11e8-8f66-77e8eb29e066.png)

**Comment by nirajav** [comment]
Done
