### ISSUE TITLE
Page - About - Our Community

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/girl-coders#73]
- **Page Information**

URL: http://dev.girlscoutcoders.org/our-people

**Comment by wpsam** [comment]
@apekshasharma27  I know you working on it. but I just created a page http://dev.girlscoutcoders.org/badge-vc/. If it is ok. we can replace current badge page.

**Comment by Code4SocialGood** [comment]
Please replace the current badge page with http://dev.girlscoutcoders.org/badge-vc/.

**Comment by Code4SocialGood** [comment]
Please replace right panel images with:

![brownie](https://user-images.githubusercontent.com/24813620/37864155-d27adbbc-2f38-11e8-8e43-5f7fc0eb5557.jpg)
![junior](https://user-images.githubusercontent.com/24813620/37864159-d5e7ec22-2f38-11e8-951e-1a63339ede9b.jpg)
![senior](https://user-images.githubusercontent.com/24813620/37864160-d8941a22-2f38-11e8-9161-d016691ce11c.jpg)
![cadet](https://user-images.githubusercontent.com/24813620/37864163-dc1332d2-2f38-11e8-9546-236f2cbcc5a8.jpg)

**Comment by Code4SocialGood** [comment]
- **Please replace left panel badge images:**

![image](https://user-images.githubusercontent.com/24813620/37864178-20af5f60-2f39-11e8-8ca0-5da675533518.png)
![image](https://user-images.githubusercontent.com/24813620/37864183-35b894b2-2f39-11e8-8511-7a45fa4f2616.png)
![image](https://user-images.githubusercontent.com/24813620/37864184-38969300-2f39-11e8-8634-a5c32c83b88f.png)
![image](https://user-images.githubusercontent.com/24813620/37864187-4290f8e6-2f39-11e8-92cc-e8c610143820.png)

**Comment by Code4SocialGood** [comment]
- **Remove the background color for description section.**

- **Change text from "Age Group" to "Grade Level".**

![image](https://user-images.githubusercontent.com/24813620/37864221-cfc57430-2f39-11e8-838a-22a3872f3960.png)
![image](https://user-images.githubusercontent.com/24813620/37864249-01cf1f9e-2f3a-11e8-98be-ef644811b103.png)

**Comment by Code4SocialGood** [comment]
Please remove Digital Photographer and Digital Movie Maker sections. We won't provide those two badges.

![image](https://user-images.githubusercontent.com/24813620/38099934-81750e38-3341-11e8-9f80-a8f51df26286.png)

**Comment by nirajav** [comment]
done

**Comment by Code4SocialGood** [comment]
Please develop this web page.

**Comment by Code4SocialGood** [comment]
- **Please display the images with smaller size, and central aligned.**

![image](https://user-images.githubusercontent.com/24813620/38748582-34179d70-3f14-11e8-83f8-6dc64c2b0365.png)
