### ISSUE TITLE
Page - About - Blog

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/girl-coders#77]
- **Page Information** 

URL: http://dev.girlscoutcoders.org/blog/

**Comment by nirajav** [comment]
Done

**Comment by Code4SocialGood** [comment]
Please develop this web page.

**Comment by Code4SocialGood** [comment]
**Please post the first blog**

[GSC Blog 1.docx](https://github.com/Code4SocialGood/girl-coders/files/1887819/GSC.Blog.1.docx)

**Comment by Code4SocialGood** [comment]
**Blog Content: http://dev.girlscoutcoders.org/introduction/
Please remove the Comments section.**

![image](https://user-images.githubusercontent.com/24813620/39091958-01c999b4-45c6-11e8-8b56-bab77a5af64b.png)

**Comment by Code4SocialGood** [comment]
- **Blog Page Implementation**

The Blog page is currently coded manually, that is:
- Blog page to display posts. Each post has an image, title, post date, and first couple lines of description
- Click on the blog title will launch the post page

If we need to add a new post, we have to modify this blog page manually. In addition, we show first couple lines of post by arbitrarily trim the text. This is not an ideal way of handle posts.

Please research on how the blog page should be implemented, so that:
- When a new post is created, it automatically shows  up in the blog page
- The post description trimming is handled nicely (by the UI function to take first couple lines)

**Comment by Lisajtx** [comment]
Took out comments section on Introduction page. Close out this part of Issue #77?

**Comment by Lisajtx** [comment]
Changed settings so that all Posts show up on the Blog page. Please test # 77.

**Comment by Code4SocialGood** [comment]
Change Request: 
1. Please add date, and author, to the blog template.
2. For the post of "An Introduction to Girl Scout Coders", date is "Jan 19, 2018", author is "Joe"

**Comment by Code4SocialGood** [comment]
**Change Request**
Please upload submit the new post attached.
[Blog_What are Badges.docx](https://github.com/Code4SocialGood/girl-coders/files/1945392/Blog_What.are.Badges.docx)

**Comment by Lisajtx** [comment]
Added new Blog Post on patches, new picture on Introduction Post, and Time Stamp for blog posts. 
I'm not sure how to add the author automatically, but maybe just add it manually when a post is created?
I removed test posts.
Not sure what is meant by "When click the post, please upload the picture on the post page also."
Please check pages; thanks! Lisa

**Comment by Code4SocialGood** [comment]
**Page: http://dev.girlscoutcoders.org/about/blog/**

1. Please display the pictures for the 2 most recent posts
What Are Badges
An Introduction to Girl Scout Coders

2. Please remove the test posts, they still show on the blog page.

3. The Author name is merged with post content. Please remove author names, we won't display them  at all.

**Comment by Lisajtx** [comment]
Please check changes now. Thanks!

**Comment by Code4SocialGood** [comment]
Could we have the posts on blog page only display first couple lines of text?

**Comment by Code4SocialGood** [comment]
Could we add DATE for the post of "An Introduction to Girl Scout Coders" on the blog page?

**Comment by Code4SocialGood** [comment]
On the individual post page: http://dev.girlscoutcoders.org/introduction/
Please add space between DATE and Picture.

![image](https://user-images.githubusercontent.com/24813620/39278203-8b60373e-48b7-11e8-9b73-bb97aa52e8ce.png)

**Comment by Lisajtx** [comment]
I moved the picture down, so date is displayed better. I thought you wanted pictures on "blog" page, so inserted full text. Now there are just a few lines showing ;) Is that OK? Lisa

**Comment by Code4SocialGood** [comment]
Sorry for the confusing in the change request!

On the blog page, for each of the post, we:  
- either display picture + full text, or,
- display no picture + a few line of text

It is not feasible:
- display picture + a few line of text

Please confirm my understand is correct.

**Comment by Code4SocialGood** [comment]
I should add a picture to describe myself better. For each post on the blog, are we able to have:
1. Date
2. A picture
3. A few lines of text
If we are not able to implement as above, that's fine, we will leave the blog page as it is, it is great already.

![image](https://user-images.githubusercontent.com/24813620/39279977-06ad325c-48c2-11e8-8dc6-cb1c577203ef.png)

**Comment by Lisajtx** [comment]
I'm not sure we can add the picture and a few lines of text. If you go to Appearance -> Customize -> Blog, you can see the options. I don't see anything about displaying pictures.

**Comment by Code4SocialGood** [comment]
Still curious how they did it in the demo app: http://test.girlscoutcoders.org/blog-2/

**Comment by Code4SocialGood** [comment]
I ended up removing the featured image. The size of image is so large that it doesn't look good. 
See here: http://test.girlscoutcoders.org/introduction/, compare the look and feel with: http://dev.girlscoutcoders.org/introduction/

We are done with the blog page. Looks nice. Thank you!
