### ISSUE TITLE
Page - Coding Clubs

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/girl-coders#85]
- **Current Page**

![image](https://user-images.githubusercontent.com/24813620/37258962-db21d9fe-254d-11e8-9c21-22c1c3c27ae2.png)

- **Change To** 

![image](https://user-images.githubusercontent.com/24813620/37258960-ceee6e2c-254d-11e8-97ba-c787dbec80a2.png)

Note:
1. Remove the border
2. Replace the images from this page: http://www.girlscouts.org/en/our-program/grade-levels.html
(You can just cut and paste the images, the image doesn't need to be high quality)

**Comment by nirajav** [comment]
done
