### ISSUE TITLE
Age Group Level

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/girl-coders#86]
1. Please refer to Age Group Level: http://www.girlscouts.org/en/our-program/grade-levels.html

2. Please develop image icons for age groups similar like below:
![image](https://user-images.githubusercontent.com/24813620/37259042-223d13fc-254f-11e8-9b68-7610a31999e4.png)
![image](https://user-images.githubusercontent.com/24813620/37259044-2bee1004-254f-11e8-9248-8c43b68add25.png)
![image](https://user-images.githubusercontent.com/24813620/37259045-3173b79a-254f-11e8-804d-f62c1391af98.png)
![image](https://user-images.githubusercontent.com/24813620/37259048-36cf5924-254f-11e8-8b1f-365360f8a3ee.png)
![image](https://user-images.githubusercontent.com/24813620/37259050-3b997494-254f-11e8-9352-117ffbd6dffa.png)
![image](https://user-images.githubusercontent.com/24813620/37259053-4277fc5e-254f-11e8-9b9a-2ff78c114413.png)

3. The image icons requirement
- Shape: feel free to choose any shape
- Color: please use the same color as the reference page (http://www.girlscouts.org/en/our-program/grade-levels.html), those color matters
- Name of the level: please include the name of the levels (Daisey, Brownie, etc) 
 - Grade: please include the text of the grade levels (grades k-1, etc)

4. Please see below the pages we are going to use these image icons:
![image](https://user-images.githubusercontent.com/24813620/37259060-66149fc8-254f-11e8-99be-a07ddefd2c95.png)

![image](https://user-images.githubusercontent.com/24813620/37259061-73122bfa-254f-11e8-975b-edf63844cd39.png)

![image](https://user-images.githubusercontent.com/24813620/37259067-8e18b158-254f-11e8-9da9-4fba6848182d.png)

5. After complete, please add a comment to this Github issue to upload the image icons.

**Comment by cdevespa** [comment]
![ambassadors](https://user-images.githubusercontent.com/26753550/37796845-7d793528-2dd5-11e8-9337-ca38d3df0868.png)
![brownies](https://user-images.githubusercontent.com/26753550/37796846-7d956cfc-2dd5-11e8-94ab-832cd674cb58.png)
![cadets](https://user-images.githubusercontent.com/26753550/37796847-7daba1f2-2dd5-11e8-8b88-e27af6c88164.png)
![daisies](https://user-images.githubusercontent.com/26753550/37796848-7dc220a8-2dd5-11e8-9577-9ae68f443be8.png)
![juniors](https://user-images.githubusercontent.com/26753550/37796849-7dd98bee-2dd5-11e8-9dd5-6a2098a3a520.png)
![seniors](https://user-images.githubusercontent.com/26753550/37796850-7df4140a-2dd5-11e8-86b1-10beff68f141.png)

**Comment by Code4SocialGood** [comment]
![daisies](https://user-images.githubusercontent.com/24813620/37804311-a9b2411c-2e01-11e8-9f79-de4b9da9963f.png)
