### ISSUE TITLE
Page - App Inventor - Rearrange Video

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/girl-coders#88]
Please arrange text description to be on the left, and video to be on the right.

- **AS-IS**
![image](https://user-images.githubusercontent.com/24813620/37320148-59787a68-2640-11e8-8885-2ca261273094.png)

- **TO-BE**
![image](https://user-images.githubusercontent.com/24813620/37320247-d6136998-2640-11e8-80a3-dfd63bfdb02e.png)

**Comment by nirajav** [comment]
Done
