### ISSUE TITLE
Footer - Social Media Section

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/girl-coders#96]
1. Please remove the search field.
2. Please make the social media icons smaller. They don't look good with the current big size. 

![image](https://user-images.githubusercontent.com/24813620/37863984-df2d96c2-2f35-11e8-9fe7-11ee4189eaf9.png)

**Comment by wpsam** [comment]
This issue is solved

**Comment by Code4SocialGood** [comment]
1. Please remove the search field.
2. Please make the social media icons smaller. They don't look good with the current big size. 

![image](https://user-images.githubusercontent.com/24813620/37863984-df2d96c2-2f35-11e8-9fe7-11ee4189eaf9.png)
